import { useState, useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { providers } from "ethers";
import styles from "../styles/Home.module.css";
import { Web3Provider } from "@ethersproject/providers";

const Home: NextPage = () => {
  const [isConnected, setIsConnected] = useState(false);
  const [provider, setProvider] = useState<Web3Provider>();
  const [loading, setLoading] = useState(false);
  const [currentAccount, setCurrentAccount] = useState("");

  // To automatically connect your wallet if you've connected before
  useEffect(() => {
    const checkIfConnected = async () => {
      const p = new providers.Web3Provider(window.ethereum);
      const accounts = await p?.listAccounts();

      if (accounts?.length !== 0) {
        setCurrentAccount(accounts[0]);
        setIsConnected(true);
      } else {
        setIsConnected(false);
      }
    };

    checkIfConnected();
  }, []);

  // For handling account changes
  useEffect(() => {
    const handleAccountChange = async () => {
      if (provider) {
        const accounts = await provider.listAccounts();
        if (accounts.length !== 0) {
          setCurrentAccount(accounts[0]);
        } else {
          setIsConnected(false);
        }
      }
    };

    if (isConnected) {
      window.ethereum.on("accountsChanged", handleAccountChange);
    }

    return () => {
      if (isConnected) {
        window.ethereum.removeListener("accountsChanged", handleAccountChange);
      }
    };
  }, [isConnected, currentAccount]);


  // Connect wallet
  const connectWallet = async () => {
    setLoading(true);

    try {
      await window.ethereum.request({ method: "eth_requestAccounts" });
      const _provider = new providers.Web3Provider(window.ethereum);
      setProvider(_provider);

      const accounts = await _provider.listAccounts();
      setCurrentAccount(accounts[0]);

      setIsConnected(true);
    } catch (e) {
      console.error(e);
    }
    setLoading(false);
  };

  const addAddressToWhitelist = async () => {

  };

  return (
    <div className={styles.container}>
      <Head>
        <title>NFT Collection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {!isConnected ? (
          <button onClick={connectWallet}>
            {loading ? "Loading..." : "Connect"}
          </button>
        ) : (
          <p>Connected with: {currentAccount}</p>
        )}
      </main>
    </div>
  );
};

export default Home;
